# Generated by Django 2.0 on 2021-10-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='adscripcion',
            field=models.TextField(default='Colegio'),
            preserve_default=False,
        ),
    ]
