# Generated by Django 2.0 on 2021-12-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_parentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.PositiveIntegerField()),
                ('group_id', models.PositiveIntegerField()),
            ],
        ),
    ]
