# Generated by Django 2.0 on 2021-12-18 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('census', '0003_parentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentgroup',
            name='voters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
