# Generated by Django 2.0 on 2021-12-17 17:14

import census.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING')], default=census.models.RequestStatus('PENDING'), max_length=255),
        ),
    ]
