# Generated by Django 2.0 on 2021-12-20 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_parentgroup_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentgroup',
            name='voters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
