# Generated by Django 2.0 on 2022-01-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('parent_voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='voting.Voting')),
            ],
        ),
    ]
