# Generated by Django 2.0 on 2022-01-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20220103_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childvoting',
            name='voters',
        ),
    ]
