# Generated by Django 2.0 on 2022-01-03 16:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_childvoting_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='childvoting',
            name='postproc',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childvoting',
            name='tally',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childvoting',
            name='group',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='census.ParentGroup'),
        ),
    ]
