# Generated by Django 2.0 on 2021-12-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voting_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
