# Generated by Django 2.0 on 2021-12-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voting_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SO', 'Single_Option'), ('MC', 'Multiple_Choice'), ('RK', 'Ranking')], default='SO', max_length=2),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='points',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
