# Generated by Django 2.0 on 2021-12-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20211208_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='points',
        ),
    ]
