# Generated by Django 2.0 on 2021-12-21 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_voting_deadline'),
        ('voting', '0006_remove_questionoption_points'),
    ]

    operations = [
    ]
