# Generated by Django 2.0 on 2021-12-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_remove_questionoption_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SO', 'Single_Option'), ('MC', 'Multiple_Choice')], default='SO', max_length=2),
        ),
    ]
