# Generated by Django 2.0 on 2021-12-22 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20211221_1217'),
        ('voting', '0007_merge_20211222_0057'),
    ]

    operations = [
    ]
